apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.env }}
spec:
  selector:
    app: {{ .Chart.Name }}-{{ .Values.env }}
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.targetPort }}
  type: LoadBalancer