SET GLOBAL local_infile = 1;


LOAD DATA LOCAL INFILE './mock_data/AuthenticationInformation1000.csv' INTO TABLE AFFORDABLE.AuthenticationInformation FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './mock_data/Emails1000.csv' INTO TABLE AFFORDABLE.emails FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './mock_data/Organization1000.csv' INTO TABLE AFFORDABLE.organization FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './mock_data/Finances1000.csv' INTO TABLE AFFORDABLE.finances FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './mock_data/Healthcare1000.csv' INTO TABLE AFFORDABLE.healthcare FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './mock_data/IdentificationInformation1000.csv' INTO TABLE AFFORDABLE.identificationInformation FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './mock_data/InformationProvider1000.csv' INTO TABLE AFFORDABLE.informationProvider FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './mock_data/Insurance1000.csv' INTO TABLE AFFORDABLE.insurance FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './mock_data/LegalName1000.csv' INTO TABLE AFFORDABLE.legalName FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './mock_data/MarriageInformation1000.csv' INTO TABLE AFFORDABLE.marriageInformation FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './mock_data/PhoneNumbers1000.csv' INTO TABLE AFFORDABLE.phoneNumbers FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './mock_data/PreviousLegalNames20.csv' INTO TABLE AFFORDABLE.legalName FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './mock_data/SecondaryPhoneNumbers200.csv' INTO TABLE AFFORDABLE.phoneNumbers FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './mock_data/SexAndEthnicity1000.csv' INTO TABLE AFFORDABLE.sexAndEthnicity FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './mock_data/TertiaryPhoneNumbers30.csv' INTO TABLE AFFORDABLE.phoneNumbers FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './mock_data/UserAddress1000.csv' INTO TABLE AFFORDABLE.userAddress FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;


